////////////////////////////////////////////////////////////////////////
//
// CAEX_ClassModel-typeinfo.cpp
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#include "StdAfx.h"
#include "CAEX_ClassModel-typeinfo.h"
#include "../Altova/xs-types.h"

namespace CAEX_ClassModel
{

const altova::Binder binder = { namespaces, types, members, facets };

// Array of all namespaces with pointers to types:
const altova::NamespaceInfo namespaces[] = 
{
	{ &binder, _T(""), _T(""), _altova_tif, _altova_til },
	{ &binder, _T("http://www.w3.org/2001/XMLSchema"), _T("xs"), _altova_tif_xs, _altova_til_xs },
	{ 0 },
};

// Array of all types with pointers to members:
const altova::TypeInfo types[] = 
{
	{ &binder, _altova_ni, _T("AttributeType"), _altova_ti_altova_CAEXObject, _altova_mif_altova_AttributeType, _altova_mil_altova_AttributeType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("AttributeValueRequirementType"), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_AttributeValueRequirementType, _altova_mil_altova_AttributeValueRequirementType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("CAEXBasicObject"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CAEXBasicObject, _altova_mil_altova_CAEXBasicObject,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("CAEXObject"), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_CAEXObject, _altova_mil_altova_CAEXObject,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("ChangeMode"), _altova_ti_xs_altova_Cstring, _altova_mif_altova_ChangeMode, _altova_mil_altova_ChangeMode,  0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T("InterfaceClassType"), _altova_ti_altova_CAEXObject, _altova_mif_altova_InterfaceClassType, _altova_mil_altova_InterfaceClassType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("InterfaceFamilyType"), _altova_ti_altova_InterfaceClassType, _altova_mif_altova_InterfaceFamilyType, _altova_mil_altova_InterfaceFamilyType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("InternalElementType"), _altova_ti_altova_SystemUnitClassType, _altova_mif_altova_InternalElementType, _altova_mil_altova_InternalElementType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("MappingType"), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_MappingType, _altova_mil_altova_MappingType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("RoleClassType"), _altova_ti_altova_CAEXObject, _altova_mif_altova_RoleClassType, _altova_mil_altova_RoleClassType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("RoleFamilyType"), _altova_ti_altova_RoleClassType, _altova_mif_altova_RoleFamilyType, _altova_mil_altova_RoleFamilyType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SystemUnitClassType"), _altova_ti_altova_CAEXObject, _altova_mif_altova_SystemUnitClassType, _altova_mil_altova_SystemUnitClassType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SystemUnitFamilyType"), _altova_ti_altova_SystemUnitClassType, _altova_mif_altova_SystemUnitFamilyType, _altova_mil_altova_SystemUnitFamilyType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("CAEX_ClassModel"), ~0, _altova_mif_altova_CAEX_ClassModel, _altova_mil_altova_CAEX_ClassModel,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_CAEXFileType, _altova_mil_altova_CAEXFileType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_CstringType, _altova_mif_altova_DescriptionType, _altova_mil_altova_DescriptionType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_CstringType, _altova_mif_altova_VersionType, _altova_mil_altova_VersionType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_RevisionType, _altova_mil_altova_RevisionType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_CstringType, _altova_mif_altova_CopyrightType, _altova_mil_altova_CopyrightType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_ExternalReferenceType, _altova_mil_altova_ExternalReferenceType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXObject, _altova_mif_altova_InstanceHierarchyType, _altova_mil_altova_InstanceHierarchyType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXObject, _altova_mif_altova_InterfaceClassLibType, _altova_mil_altova_InterfaceClassLibType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXObject, _altova_mif_altova_RoleClassLibType, _altova_mil_altova_RoleClassLibType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXObject, _altova_mif_altova_SystemUnitClassLibType, _altova_mil_altova_SystemUnitClassLibType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_Cstring, _altova_mif_altova_AttributeDataTypeType, _altova_mil_altova_AttributeDataTypeType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_RefSemanticType, _altova_mil_altova_RefSemanticType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_CanyType, _altova_mif_altova_OrdinalScaledTypeType, _altova_mil_altova_OrdinalScaledTypeType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_CanyType, _altova_mif_altova_NominalScaledTypeType, _altova_mil_altova_NominalScaledTypeType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_CanyType, _altova_mif_altova_UnknownTypeType, _altova_mil_altova_UnknownTypeType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_SupportedRoleClassType, _altova_mil_altova_SupportedRoleClassType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXObject, _altova_mif_altova_InternalLinkType, _altova_mil_altova_InternalLinkType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_RoleRequirementsType, _altova_mil_altova_RoleRequirementsType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_AttributeNameMappingType, _altova_mil_altova_AttributeNameMappingType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_CAEXBasicObject, _altova_mif_altova_InterfaceNameMappingType, _altova_mil_altova_InterfaceNameMappingType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_altova_InterfaceClassType, _altova_mif_altova_ExternalInterfaceType, _altova_mil_altova_ExternalInterfaceType,  ~0 , altova::Whitespace_Unknown },

	{ &binder, _altova_ni_xs, _T("ENTITIES"), ~0, _altova_mif_xs_altova_CENTITIES, _altova_mil_xs_altova_CENTITIES,  5 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni_xs, _T("ENTITY"), _altova_ti_xs_altova_CNCName, _altova_mif_xs_altova_CENTITY, _altova_mil_xs_altova_CENTITY,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("ID"), _altova_ti_xs_altova_CNCName, _altova_mif_xs_altova_CID, _altova_mil_xs_altova_CID,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("IDREF"), _altova_ti_xs_altova_CNCName, _altova_mif_xs_altova_CIDREF, _altova_mil_xs_altova_CIDREF,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("IDREFS"), ~0, _altova_mif_xs_altova_CIDREFS, _altova_mil_xs_altova_CIDREFS,  7 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni_xs, _T("NCName"), _altova_ti_xs_altova_CName, _altova_mif_xs_altova_CNCName, _altova_mil_xs_altova_CNCName,  9 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("NMTOKEN"), _altova_ti_xs_altova_Ctoken, _altova_mif_xs_altova_CNMTOKEN, _altova_mil_xs_altova_CNMTOKEN,  11 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("NMTOKENS"), ~0, _altova_mif_xs_altova_CNMTOKENS, _altova_mil_xs_altova_CNMTOKENS,  13 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni_xs, _T("NOTATION"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CNOTATION, _altova_mil_xs_altova_CNOTATION,  16 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("Name"), _altova_ti_xs_altova_Ctoken, _altova_mif_xs_altova_CName, _altova_mil_xs_altova_CName,  18 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("QName"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CQName, _altova_mil_xs_altova_CQName,  20 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("anySimpleType"), ~0, _altova_mif_xs_altova_CanySimpleType, _altova_mil_xs_altova_CanySimpleType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("anyType"), ~0, _altova_mif_xs_altova_CanyType, _altova_mil_xs_altova_CanyType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("anyURI"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CanyURI, _altova_mil_xs_altova_CanyURI,  22 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("base64Binary"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cbase64Binary, _altova_mil_xs_altova_Cbase64Binary,  24 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("boolean"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cboolean, _altova_mil_xs_altova_Cboolean,  26 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("byte"), _altova_ti_xs_altova_Cshort, _altova_mif_xs_altova_Cbyte, _altova_mil_xs_altova_Cbyte,  28 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("date"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cdate, _altova_mil_xs_altova_Cdate,  31 , altova::Whitespace_Collapse, &altova::DateFormatter },
	{ &binder, _altova_ni_xs, _T("dateTime"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CdateTime, _altova_mil_xs_altova_CdateTime,  33 , altova::Whitespace_Collapse, &altova::DateTimeFormatter },
	{ &binder, _altova_ni_xs, _T("decimal"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cdecimal, _altova_mil_xs_altova_Cdecimal,  35 , altova::Whitespace_Collapse, &altova::DecimalFormatter },
	{ &binder, _altova_ni_xs, _T("double"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cdouble, _altova_mil_xs_altova_Cdouble,  37 , altova::Whitespace_Collapse, &altova::DoubleFormatter },
	{ &binder, _altova_ni_xs, _T("duration"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cduration, _altova_mil_xs_altova_Cduration,  39 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("float"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cfloat, _altova_mil_xs_altova_Cfloat,  41 , altova::Whitespace_Collapse, &altova::DoubleFormatter },
	{ &binder, _altova_ni_xs, _T("gDay"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgDay, _altova_mil_xs_altova_CgDay,  43 , altova::Whitespace_Collapse, &altova::GDayFormatter },
	{ &binder, _altova_ni_xs, _T("gMonth"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgMonth, _altova_mil_xs_altova_CgMonth,  45 , altova::Whitespace_Collapse, &altova::GMonthFormatter },
	{ &binder, _altova_ni_xs, _T("gMonthDay"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgMonthDay, _altova_mil_xs_altova_CgMonthDay,  47 , altova::Whitespace_Collapse, &altova::GMonthDayFormatter },
	{ &binder, _altova_ni_xs, _T("gYear"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgYear, _altova_mil_xs_altova_CgYear,  49 , altova::Whitespace_Collapse, &altova::GYearFormatter },
	{ &binder, _altova_ni_xs, _T("gYearMonth"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgYearMonth, _altova_mil_xs_altova_CgYearMonth,  51 , altova::Whitespace_Collapse, &altova::GYearMonthFormatter },
	{ &binder, _altova_ni_xs, _T("hexBinary"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_ChexBinary, _altova_mil_xs_altova_ChexBinary,  53 , altova::Whitespace_Collapse, &altova::HexBinaryFormatter },
	{ &binder, _altova_ni_xs, _T("int"), _altova_ti_xs_altova_Clong, _altova_mif_xs_altova_Cint, _altova_mil_xs_altova_Cint,  55 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("integer"), _altova_ti_xs_altova_Cdecimal, _altova_mif_xs_altova_Cinteger, _altova_mil_xs_altova_Cinteger,  58 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("language"), _altova_ti_xs_altova_Ctoken, _altova_mif_xs_altova_Clanguage, _altova_mil_xs_altova_Clanguage,  61 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("long"), _altova_ti_xs_altova_Cinteger, _altova_mif_xs_altova_Clong, _altova_mil_xs_altova_Clong,  63 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("negativeInteger"), _altova_ti_xs_altova_CnonPositiveInteger, _altova_mif_xs_altova_CnegativeInteger, _altova_mil_xs_altova_CnegativeInteger,  66 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("nonNegativeInteger"), _altova_ti_xs_altova_Cinteger, _altova_mif_xs_altova_CnonNegativeInteger, _altova_mil_xs_altova_CnonNegativeInteger,  68 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("nonPositiveInteger"), _altova_ti_xs_altova_Cinteger, _altova_mif_xs_altova_CnonPositiveInteger, _altova_mil_xs_altova_CnonPositiveInteger,  70 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("normalizedString"), _altova_ti_xs_altova_Cstring, _altova_mif_xs_altova_CnormalizedString, _altova_mil_xs_altova_CnormalizedString,  72 , altova::Whitespace_Replace, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("positiveInteger"), _altova_ti_xs_altova_CnonNegativeInteger, _altova_mif_xs_altova_CpositiveInteger, _altova_mil_xs_altova_CpositiveInteger,  74 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("short"), _altova_ti_xs_altova_Cint, _altova_mif_xs_altova_Cshort, _altova_mil_xs_altova_Cshort,  76 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("string"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cstring, _altova_mil_xs_altova_Cstring,  79 , altova::Whitespace_Preserve, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("time"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Ctime, _altova_mil_xs_altova_Ctime,  81 , altova::Whitespace_Collapse, &altova::TimeFormatter },
	{ &binder, _altova_ni_xs, _T("token"), _altova_ti_xs_altova_CnormalizedString, _altova_mif_xs_altova_Ctoken, _altova_mil_xs_altova_Ctoken,  83 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedByte"), _altova_ti_xs_altova_CunsignedShort, _altova_mif_xs_altova_CunsignedByte, _altova_mil_xs_altova_CunsignedByte,  85 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedInt"), _altova_ti_xs_altova_CunsignedLong, _altova_mif_xs_altova_CunsignedInt, _altova_mil_xs_altova_CunsignedInt,  87 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedLong"), _altova_ti_xs_altova_CnonNegativeInteger, _altova_mif_xs_altova_CunsignedLong, _altova_mil_xs_altova_CunsignedLong,  89 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedShort"), _altova_ti_xs_altova_CunsignedInt, _altova_mif_xs_altova_CunsignedShort, _altova_mil_xs_altova_CunsignedShort,  91 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T(""), ~0, _altova_mif_xs_altova_CstringType, _altova_mil_xs_altova_CstringType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T(""), ~0, _altova_mif_xs_altova_CdateTimeType, _altova_mil_xs_altova_CdateTimeType,  ~0 , altova::Whitespace_Unknown, &altova::DateTimeFormatter },

{ 0 },
};

const altova::MemberInfo members[] = 
{
	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_AttributeType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_AttributeType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_AttributeType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Unit"), _altova_ti_altova_AttributeType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("AttributeDataType"), _altova_ti_altova_AttributeType, _altova_ti_altova_AttributeDataTypeType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_AttributeType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_AttributeType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_AttributeType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_AttributeType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_AttributeType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("DefaultValue"), _altova_ti_altova_AttributeType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Value"), _altova_ti_altova_AttributeType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("RefSemantic"), _altova_ti_altova_AttributeType, _altova_ti_altova_RefSemanticType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Constraint"), _altova_ti_altova_AttributeType, _altova_ti_altova_AttributeValueRequirementType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_AttributeType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("OrdinalScaledType"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_OrdinalScaledTypeType, MemberFlags_None, 1, 1 },
	{ &binder, _T(""), _T("NominalScaledType"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_NominalScaledTypeType, MemberFlags_None, 1, 1 },
	{ &binder, _T(""), _T("UnknownType"), _altova_ti_altova_AttributeValueRequirementType, _altova_ti_altova_UnknownTypeType, MemberFlags_None, 1, 1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_CAEXBasicObject, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_CAEXBasicObject, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_CAEXBasicObject, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_CAEXBasicObject, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_CAEXBasicObject, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_CAEXBasicObject, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_CAEXObject, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_CAEXObject, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_CAEXObject, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_CAEXObject, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_CAEXObject, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_CAEXObject, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_CAEXObject, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_CAEXObject, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_InterfaceClassType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_InterfaceClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_InterfaceClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefBaseClassPath"), _altova_ti_altova_InterfaceClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_InterfaceClassType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_InterfaceClassType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_InterfaceClassType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_InterfaceClassType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_InterfaceClassType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_InterfaceClassType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefBaseClassPath"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InterfaceClass"), _altova_ti_altova_InterfaceFamilyType, _altova_ti_altova_InterfaceFamilyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_InternalElementType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_InternalElementType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_InternalElementType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefBaseSystemUnitPath"), _altova_ti_altova_InternalElementType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_InternalElementType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_InternalElementType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_InternalElementType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_InternalElementType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_InternalElementType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_InternalElementType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("ExternalInterface"), _altova_ti_altova_InternalElementType, _altova_ti_altova_InterfaceClassType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InternalElement"), _altova_ti_altova_InternalElementType, _altova_ti_altova_InternalElementType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("SupportedRoleClass"), _altova_ti_altova_InternalElementType, _altova_ti_altova_SupportedRoleClassType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InternalLink"), _altova_ti_altova_InternalElementType, _altova_ti_altova_InternalLinkType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("RoleRequirements"), _altova_ti_altova_InternalElementType, _altova_ti_altova_RoleRequirementsType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("MappingObject"), _altova_ti_altova_InternalElementType, _altova_ti_altova_MappingType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_MappingType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_MappingType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_MappingType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_MappingType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_MappingType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_MappingType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("AttributeNameMapping"), _altova_ti_altova_MappingType, _altova_ti_altova_AttributeNameMappingType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InterfaceNameMapping"), _altova_ti_altova_MappingType, _altova_ti_altova_InterfaceNameMappingType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_RoleClassType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_RoleClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_RoleClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefBaseClassPath"), _altova_ti_altova_RoleClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_RoleClassType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_RoleClassType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_RoleClassType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_RoleClassType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_RoleClassType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_RoleClassType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("ExternalInterface"), _altova_ti_altova_RoleClassType, _altova_ti_altova_ExternalInterfaceType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_RoleFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_RoleFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefBaseClassPath"), _altova_ti_altova_RoleFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_RoleFamilyType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("ExternalInterface"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_ExternalInterfaceType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("RoleClass"), _altova_ti_altova_RoleFamilyType, _altova_ti_altova_RoleFamilyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_SystemUnitClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_SystemUnitClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_SystemUnitClassType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("ExternalInterface"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_InterfaceClassType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InternalElement"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_InternalElementType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("SupportedRoleClass"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_SupportedRoleClassType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InternalLink"), _altova_ti_altova_SystemUnitClassType, _altova_ti_altova_InternalLinkType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefBaseClassPath"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("ExternalInterface"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_InterfaceClassType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InternalElement"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_InternalElementType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("SupportedRoleClass"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_SupportedRoleClassType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InternalLink"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_InternalLinkType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("SystemUnitClass"), _altova_ti_altova_SystemUnitFamilyType, _altova_ti_altova_SystemUnitFamilyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("CAEXFile"), _altova_ti_altova_CAEX_ClassModel, _altova_ti_altova_CAEXFileType, MemberFlags_None, 0, 0 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("FileName"), _altova_ti_altova_CAEXFileType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("SchemaVersion"), _altova_ti_altova_CAEXFileType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_CAEXFileType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("ExternalReference"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_ExternalReferenceType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InstanceHierarchy"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_InstanceHierarchyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InterfaceClassLib"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_InterfaceClassLibType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("RoleClassLib"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_RoleClassLibType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("SystemUnitClassLib"), _altova_ti_altova_CAEXFileType, _altova_ti_altova_SystemUnitClassLibType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T(""), _altova_ti_altova_DescriptionType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, -1 },
	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_DescriptionType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T(""), _T(""), _altova_ti_altova_VersionType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, -1 },
	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_VersionType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_RevisionType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_RevisionType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_RevisionType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_RevisionType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_RevisionType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_RevisionType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("RevisionDate"), _altova_ti_altova_RevisionType, _altova_ti_xs_altova_CdateTimeType, MemberFlags_None, 1, 1 },
	{ &binder, _T(""), _T("OldVersion"), _altova_ti_altova_RevisionType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("NewVersion"), _altova_ti_altova_RevisionType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AuthorName"), _altova_ti_altova_RevisionType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 1, 1 },
	{ &binder, _T(""), _T("Comment"), _altova_ti_altova_RevisionType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T(""), _altova_ti_altova_CopyrightType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, -1 },
	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_CopyrightType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_ExternalReferenceType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Path"), _altova_ti_altova_ExternalReferenceType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Alias"), _altova_ti_altova_ExternalReferenceType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_ExternalReferenceType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_ExternalReferenceType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_ExternalReferenceType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_ExternalReferenceType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_ExternalReferenceType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InternalElement"), _altova_ti_altova_InstanceHierarchyType, _altova_ti_altova_InternalElementType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("InterfaceClass"), _altova_ti_altova_InterfaceClassLibType, _altova_ti_altova_InterfaceFamilyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_RoleClassLibType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_RoleClassLibType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_RoleClassLibType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_RoleClassLibType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_RoleClassLibType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_RoleClassLibType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_RoleClassLibType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_RoleClassLibType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("RoleClass"), _altova_ti_altova_RoleClassLibType, _altova_ti_altova_RoleFamilyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("SystemUnitClass"), _altova_ti_altova_SystemUnitClassLibType, _altova_ti_altova_SystemUnitFamilyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_RefSemanticType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("CorrespondingAttributePath"), _altova_ti_altova_RefSemanticType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_RefSemanticType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_RefSemanticType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_RefSemanticType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_RefSemanticType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_RefSemanticType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("RequiredMaxValue"), _altova_ti_altova_OrdinalScaledTypeType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("RequiredValue"), _altova_ti_altova_OrdinalScaledTypeType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("RequiredMinValue"), _altova_ti_altova_OrdinalScaledTypeType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("RequiredValue"), _altova_ti_altova_NominalScaledTypeType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("Requirements"), _altova_ti_altova_UnknownTypeType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 1, 1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("RefRoleClassPath"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("MappingObject"), _altova_ti_altova_SupportedRoleClassType, _altova_ti_altova_MappingType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_InternalLinkType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_InternalLinkType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_InternalLinkType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefPartnerSideA"), _altova_ti_altova_InternalLinkType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("RefPartnerSideB"), _altova_ti_altova_InternalLinkType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_InternalLinkType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_InternalLinkType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_InternalLinkType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_InternalLinkType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_InternalLinkType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_RoleRequirementsType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("RefBaseRoleClassPath"), _altova_ti_altova_RoleRequirementsType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_RoleRequirementsType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_RoleRequirementsType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_RoleRequirementsType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_RoleRequirementsType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_RoleRequirementsType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_RoleRequirementsType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("ExternalInterface"), _altova_ti_altova_RoleRequirementsType, _altova_ti_altova_InterfaceClassType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("SystemUnitAttributeName"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RoleAttributeName"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_AttributeNameMappingType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("SystemUnitInterfaceName"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RoleInterfaceName"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_InterfaceNameMappingType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("ChangeMode"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_altova_ChangeMode, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("ID"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Name"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("RefBaseClassPath"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("Description"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_altova_DescriptionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Version"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_altova_VersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("Revision"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_altova_RevisionType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Copyright"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_altova_CopyrightType, MemberFlags_None, 0, 1 },
	{ &binder, _T(""), _T("AdditionalInformation"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_xs_altova_CanyType, MemberFlags_None, 0, -1 },
	{ &binder, _T(""), _T("Attribute"), _altova_ti_altova_ExternalInterfaceType, _altova_ti_altova_AttributeType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T(""), _altova_ti_xs_altova_CanyType, _altova_ti_xs_altova_CanySimpleType, MemberFlags_IsAttribute, 0, -1 },

	{ &binder, _T(""), _T(""), _altova_ti_xs_altova_CstringType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, -1 },

	{ &binder, _T(""), _T(""), _altova_ti_xs_altova_CdateTimeType, _altova_ti_xs_altova_CdateTime, MemberFlags_IsAttribute, 0, -1 },

{ 0 },
};

const altova::FacetInfo facets[] = 
{
	// ChangeMode
	{ 0, _T("enumeration"), _T("state"), 0 }, 
	{ 0, _T("enumeration"), _T("create"), 0 }, 
	{ 0, _T("enumeration"), _T("delete"), 0 }, 
	{ 0, _T("enumeration"), _T("change"), 0 }, 
	{ 0, 0, 0, 0 },
	// ENTITIES
	{ 0, _T("minLength"), _T("1"), 1 }, 
	{ 0, 0, 0, 0 },
	// IDREFS
	{ 0, _T("minLength"), _T("1"), 1 }, 
	{ 0, 0, 0, 0 },
	// NCName
	{ 0, _T("pattern"), _T("[\\i-[:]][\\c-[:]]*"), 0 }, 
	{ 0, 0, 0, 0 },
	// NMTOKEN
	{ 0, _T("pattern"), _T("\\c+"), 0 }, 
	{ 0, 0, 0, 0 },
	// NMTOKENS
	{ 0, _T("minLength"), _T("1"), 1 }, 
	{ 0, _T("pattern"), _T("\\c+"), 0 }, 
	{ 0, 0, 0, 0 },
	// NOTATION
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// Name
	{ 0, _T("pattern"), _T("\\i\\c*"), 0 }, 
	{ 0, 0, 0, 0 },
	// QName
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// anyURI
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// base64Binary
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// boolean
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// byte
	{ 0, _T("minInclusive"), _T("-128"), 0 }, 
	{ 0, _T("maxInclusive"), _T("127"), 0 }, 
	{ 0, 0, 0, 0 },
	// date
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// dateTime
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// decimal
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// double
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// duration
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// float
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gDay
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gMonth
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gMonthDay
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gYear
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gYearMonth
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// hexBinary
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// int
	{ 0, _T("minInclusive"), _T("-2147483648"), 0 }, 
	{ 0, _T("maxInclusive"), _T("2147483647"), 0 }, 
	{ 0, 0, 0, 0 },
	// integer
	{ 0, _T("fractionDigits"), _T("0"), 0 }, 
	{ 0, _T("pattern"), _T("[\\-+]?[0-9]+"), 0 }, 
	{ 0, 0, 0, 0 },
	// language
	{ 0, _T("pattern"), _T("[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"), 0 }, 
	{ 0, 0, 0, 0 },
	// long
	{ 0, _T("minInclusive"), _T("-9223372036854775808"), 0 }, 
	{ 0, _T("maxInclusive"), _T("9223372036854775807"), 0 }, 
	{ 0, 0, 0, 0 },
	// negativeInteger
	{ 0, _T("maxInclusive"), _T("-1"), 0 }, 
	{ 0, 0, 0, 0 },
	// nonNegativeInteger
	{ 0, _T("minInclusive"), _T("0"), 0 }, 
	{ 0, 0, 0, 0 },
	// nonPositiveInteger
	{ 0, _T("maxInclusive"), _T("0"), 0 }, 
	{ 0, 0, 0, 0 },
	// normalizedString
	{ 0, _T("whitespace"), _T("replace"), 0 },
	{ 0, 0, 0, 0 },
	// positiveInteger
	{ 0, _T("minInclusive"), _T("1"), 0 }, 
	{ 0, 0, 0, 0 },
	// short
	{ 0, _T("minInclusive"), _T("-32768"), 0 }, 
	{ 0, _T("maxInclusive"), _T("32767"), 0 }, 
	{ 0, 0, 0, 0 },
	// string
	{ 0, _T("whitespace"), _T("preserve"), 0 },
	{ 0, 0, 0, 0 },
	// time
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// token
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// unsignedByte
	{ 0, _T("maxInclusive"), _T("255"), 0 }, 
	{ 0, 0, 0, 0 },
	// unsignedInt
	{ 0, _T("maxInclusive"), _T("4294967295"), 0 }, 
	{ 0, 0, 0, 0 },
	// unsignedLong
	{ 0, _T("maxInclusive"), _T("18446744073709551615"), 0 }, 
	{ 0, 0, 0, 0 },
	// unsignedShort
	{ 0, _T("maxInclusive"), _T("65535"), 0 }, 
	{ 0, 0, 0, 0 },
{ 0 },
};

}  // namespace CAEX_ClassModel
