////////////////////////////////////////////////////////////////////////
//
// CAEX_ClassModel-typeinfo.h
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef _INCLUDED_CAEX_ClassModel_typeinfo_H_
#define _INCLUDED_CAEX_ClassModel_typeinfo_H_

#include "../Altova/StructInfo.h"

#undef CAEX_ClassModel_DECLSPECIFIER

#ifdef _WIN32
#ifdef CAEX_ClassModel_EXPORTS
#define CAEX_ClassModel_DECLSPECIFIER __declspec(dllexport)
#else
#define CAEX_ClassModel_DECLSPECIFIER __declspec(dllimport)
#endif
#else  // not _WIN32
#define CAEX_ClassModel_DECLSPECIFIER
#endif // _WIN32


namespace CAEX_ClassModel
{

enum _altova_namespace_indices
{
	_altova_ni,
	_altova_ni_xs

};

enum _altova_typeinfo_indices
{
	_altova_tif,
	_altova_ti_altova_AttributeType = _altova_tif,
	_altova_ti_altova_AttributeValueRequirementType,
	_altova_ti_altova_CAEXBasicObject,
	_altova_ti_altova_CAEXObject,
	_altova_ti_altova_ChangeMode,
	_altova_ti_altova_InterfaceClassType,
	_altova_ti_altova_InterfaceFamilyType,
	_altova_ti_altova_InternalElementType,
	_altova_ti_altova_MappingType,
	_altova_ti_altova_RoleClassType,
	_altova_ti_altova_RoleFamilyType,
	_altova_ti_altova_SystemUnitClassType,
	_altova_ti_altova_SystemUnitFamilyType,
	_altova_ti_altova_CAEX_ClassModel,
	_altova_ti_altova_CAEXFileType,
	_altova_ti_altova_DescriptionType,
	_altova_ti_altova_VersionType,
	_altova_ti_altova_RevisionType,
	_altova_ti_altova_CopyrightType,
	_altova_ti_altova_ExternalReferenceType,
	_altova_ti_altova_InstanceHierarchyType,
	_altova_ti_altova_InterfaceClassLibType,
	_altova_ti_altova_RoleClassLibType,
	_altova_ti_altova_SystemUnitClassLibType,
	_altova_ti_altova_AttributeDataTypeType,
	_altova_ti_altova_RefSemanticType,
	_altova_ti_altova_OrdinalScaledTypeType,
	_altova_ti_altova_NominalScaledTypeType,
	_altova_ti_altova_UnknownTypeType,
	_altova_ti_altova_SupportedRoleClassType,
	_altova_ti_altova_InternalLinkType,
	_altova_ti_altova_RoleRequirementsType,
	_altova_ti_altova_AttributeNameMappingType,
	_altova_ti_altova_InterfaceNameMappingType,
	_altova_ti_altova_ExternalInterfaceType,
	_altova_til,

	_altova_tif_xs = _altova_til,
	_altova_ti_xs_altova_CENTITIES = _altova_tif_xs,
	_altova_ti_xs_altova_CENTITY,
	_altova_ti_xs_altova_CID,
	_altova_ti_xs_altova_CIDREF,
	_altova_ti_xs_altova_CIDREFS,
	_altova_ti_xs_altova_CNCName,
	_altova_ti_xs_altova_CNMTOKEN,
	_altova_ti_xs_altova_CNMTOKENS,
	_altova_ti_xs_altova_CNOTATION,
	_altova_ti_xs_altova_CName,
	_altova_ti_xs_altova_CQName,
	_altova_ti_xs_altova_CanySimpleType,
	_altova_ti_xs_altova_CanyType,
	_altova_ti_xs_altova_CanyURI,
	_altova_ti_xs_altova_Cbase64Binary,
	_altova_ti_xs_altova_Cboolean,
	_altova_ti_xs_altova_Cbyte,
	_altova_ti_xs_altova_Cdate,
	_altova_ti_xs_altova_CdateTime,
	_altova_ti_xs_altova_Cdecimal,
	_altova_ti_xs_altova_Cdouble,
	_altova_ti_xs_altova_Cduration,
	_altova_ti_xs_altova_Cfloat,
	_altova_ti_xs_altova_CgDay,
	_altova_ti_xs_altova_CgMonth,
	_altova_ti_xs_altova_CgMonthDay,
	_altova_ti_xs_altova_CgYear,
	_altova_ti_xs_altova_CgYearMonth,
	_altova_ti_xs_altova_ChexBinary,
	_altova_ti_xs_altova_Cint,
	_altova_ti_xs_altova_Cinteger,
	_altova_ti_xs_altova_Clanguage,
	_altova_ti_xs_altova_Clong,
	_altova_ti_xs_altova_CnegativeInteger,
	_altova_ti_xs_altova_CnonNegativeInteger,
	_altova_ti_xs_altova_CnonPositiveInteger,
	_altova_ti_xs_altova_CnormalizedString,
	_altova_ti_xs_altova_CpositiveInteger,
	_altova_ti_xs_altova_Cshort,
	_altova_ti_xs_altova_Cstring,
	_altova_ti_xs_altova_Ctime,
	_altova_ti_xs_altova_Ctoken,
	_altova_ti_xs_altova_CunsignedByte,
	_altova_ti_xs_altova_CunsignedInt,
	_altova_ti_xs_altova_CunsignedLong,
	_altova_ti_xs_altova_CunsignedShort,
	_altova_ti_xs_altova_CstringType,
	_altova_ti_xs_altova_CdateTimeType,
	_altova_til_xs


};

enum
{
	_altova_mif_altova_AttributeType,
	_altova_mi_altova_AttributeType_altova_ChangeMode = _altova_mif_altova_AttributeType,
	_altova_mi_altova_AttributeType_altova_ID,
	_altova_mi_altova_AttributeType_altova_Name,
	_altova_mi_altova_AttributeType_altova_Unit,
	_altova_mi_altova_AttributeType_altova_AttributeDataType,
	_altova_mi_altova_AttributeType_altova_Description,
	_altova_mi_altova_AttributeType_altova_Version,
	_altova_mi_altova_AttributeType_altova_Revision,
	_altova_mi_altova_AttributeType_altova_Copyright,
	_altova_mi_altova_AttributeType_altova_AdditionalInformation,
	_altova_mi_altova_AttributeType_altova_DefaultValue,
	_altova_mi_altova_AttributeType_altova_Value,
	_altova_mi_altova_AttributeType_altova_RefSemantic,
	_altova_mi_altova_AttributeType_altova_Constraint,
	_altova_mi_altova_AttributeType_altova_Attribute,
	_altova_mil_altova_AttributeType
};
enum
{
	_altova_mif_altova_AttributeValueRequirementType = _altova_mil_altova_AttributeType,
	_altova_mi_altova_AttributeValueRequirementType_altova_ChangeMode = _altova_mif_altova_AttributeValueRequirementType,
	_altova_mi_altova_AttributeValueRequirementType_altova_Name,
	_altova_mi_altova_AttributeValueRequirementType_altova_Description,
	_altova_mi_altova_AttributeValueRequirementType_altova_Version,
	_altova_mi_altova_AttributeValueRequirementType_altova_Revision,
	_altova_mi_altova_AttributeValueRequirementType_altova_Copyright,
	_altova_mi_altova_AttributeValueRequirementType_altova_AdditionalInformation,
	_altova_mi_altova_AttributeValueRequirementType_altova_OrdinalScaledType,
	_altova_mi_altova_AttributeValueRequirementType_altova_NominalScaledType,
	_altova_mi_altova_AttributeValueRequirementType_altova_UnknownType,
	_altova_mil_altova_AttributeValueRequirementType
};
enum
{
	_altova_mif_altova_CAEXBasicObject = _altova_mil_altova_AttributeValueRequirementType,
	_altova_mi_altova_CAEXBasicObject_altova_ChangeMode = _altova_mif_altova_CAEXBasicObject,
	_altova_mi_altova_CAEXBasicObject_altova_Description,
	_altova_mi_altova_CAEXBasicObject_altova_Version,
	_altova_mi_altova_CAEXBasicObject_altova_Revision,
	_altova_mi_altova_CAEXBasicObject_altova_Copyright,
	_altova_mi_altova_CAEXBasicObject_altova_AdditionalInformation,
	_altova_mil_altova_CAEXBasicObject
};
enum
{
	_altova_mif_altova_CAEXObject = _altova_mil_altova_CAEXBasicObject,
	_altova_mi_altova_CAEXObject_altova_ChangeMode = _altova_mif_altova_CAEXObject,
	_altova_mi_altova_CAEXObject_altova_ID,
	_altova_mi_altova_CAEXObject_altova_Name,
	_altova_mi_altova_CAEXObject_altova_Description,
	_altova_mi_altova_CAEXObject_altova_Version,
	_altova_mi_altova_CAEXObject_altova_Revision,
	_altova_mi_altova_CAEXObject_altova_Copyright,
	_altova_mi_altova_CAEXObject_altova_AdditionalInformation,
	_altova_mil_altova_CAEXObject
};
enum
{
	_altova_mif_altova_ChangeMode = _altova_mil_altova_CAEXObject,
	_altova_mil_altova_ChangeMode = _altova_mif_altova_ChangeMode
};
enum
{
	_altova_mif_altova_InterfaceClassType = _altova_mil_altova_ChangeMode,
	_altova_mi_altova_InterfaceClassType_altova_ChangeMode = _altova_mif_altova_InterfaceClassType,
	_altova_mi_altova_InterfaceClassType_altova_ID,
	_altova_mi_altova_InterfaceClassType_altova_Name,
	_altova_mi_altova_InterfaceClassType_altova_RefBaseClassPath,
	_altova_mi_altova_InterfaceClassType_altova_Description,
	_altova_mi_altova_InterfaceClassType_altova_Version,
	_altova_mi_altova_InterfaceClassType_altova_Revision,
	_altova_mi_altova_InterfaceClassType_altova_Copyright,
	_altova_mi_altova_InterfaceClassType_altova_AdditionalInformation,
	_altova_mi_altova_InterfaceClassType_altova_Attribute,
	_altova_mil_altova_InterfaceClassType
};
enum
{
	_altova_mif_altova_InterfaceFamilyType = _altova_mil_altova_InterfaceClassType,
	_altova_mi_altova_InterfaceFamilyType_altova_ChangeMode = _altova_mif_altova_InterfaceFamilyType,
	_altova_mi_altova_InterfaceFamilyType_altova_ID,
	_altova_mi_altova_InterfaceFamilyType_altova_Name,
	_altova_mi_altova_InterfaceFamilyType_altova_RefBaseClassPath,
	_altova_mi_altova_InterfaceFamilyType_altova_Description,
	_altova_mi_altova_InterfaceFamilyType_altova_Version,
	_altova_mi_altova_InterfaceFamilyType_altova_Revision,
	_altova_mi_altova_InterfaceFamilyType_altova_Copyright,
	_altova_mi_altova_InterfaceFamilyType_altova_AdditionalInformation,
	_altova_mi_altova_InterfaceFamilyType_altova_Attribute,
	_altova_mi_altova_InterfaceFamilyType_altova_InterfaceClass,
	_altova_mil_altova_InterfaceFamilyType
};
enum
{
	_altova_mif_altova_InternalElementType = _altova_mil_altova_InterfaceFamilyType,
	_altova_mi_altova_InternalElementType_altova_ChangeMode = _altova_mif_altova_InternalElementType,
	_altova_mi_altova_InternalElementType_altova_ID,
	_altova_mi_altova_InternalElementType_altova_Name,
	_altova_mi_altova_InternalElementType_altova_RefBaseSystemUnitPath,
	_altova_mi_altova_InternalElementType_altova_Description,
	_altova_mi_altova_InternalElementType_altova_Version,
	_altova_mi_altova_InternalElementType_altova_Revision,
	_altova_mi_altova_InternalElementType_altova_Copyright,
	_altova_mi_altova_InternalElementType_altova_AdditionalInformation,
	_altova_mi_altova_InternalElementType_altova_Attribute,
	_altova_mi_altova_InternalElementType_altova_ExternalInterface,
	_altova_mi_altova_InternalElementType_altova_InternalElement,
	_altova_mi_altova_InternalElementType_altova_SupportedRoleClass,
	_altova_mi_altova_InternalElementType_altova_InternalLink,
	_altova_mi_altova_InternalElementType_altova_RoleRequirements,
	_altova_mi_altova_InternalElementType_altova_MappingObject,
	_altova_mil_altova_InternalElementType
};
enum
{
	_altova_mif_altova_MappingType = _altova_mil_altova_InternalElementType,
	_altova_mi_altova_MappingType_altova_ChangeMode = _altova_mif_altova_MappingType,
	_altova_mi_altova_MappingType_altova_Description,
	_altova_mi_altova_MappingType_altova_Version,
	_altova_mi_altova_MappingType_altova_Revision,
	_altova_mi_altova_MappingType_altova_Copyright,
	_altova_mi_altova_MappingType_altova_AdditionalInformation,
	_altova_mi_altova_MappingType_altova_AttributeNameMapping,
	_altova_mi_altova_MappingType_altova_InterfaceNameMapping,
	_altova_mil_altova_MappingType
};
enum
{
	_altova_mif_altova_RoleClassType = _altova_mil_altova_MappingType,
	_altova_mi_altova_RoleClassType_altova_ChangeMode = _altova_mif_altova_RoleClassType,
	_altova_mi_altova_RoleClassType_altova_ID,
	_altova_mi_altova_RoleClassType_altova_Name,
	_altova_mi_altova_RoleClassType_altova_RefBaseClassPath,
	_altova_mi_altova_RoleClassType_altova_Description,
	_altova_mi_altova_RoleClassType_altova_Version,
	_altova_mi_altova_RoleClassType_altova_Revision,
	_altova_mi_altova_RoleClassType_altova_Copyright,
	_altova_mi_altova_RoleClassType_altova_AdditionalInformation,
	_altova_mi_altova_RoleClassType_altova_Attribute,
	_altova_mi_altova_RoleClassType_altova_ExternalInterface,
	_altova_mil_altova_RoleClassType
};
enum
{
	_altova_mif_altova_RoleFamilyType = _altova_mil_altova_RoleClassType,
	_altova_mi_altova_RoleFamilyType_altova_ChangeMode = _altova_mif_altova_RoleFamilyType,
	_altova_mi_altova_RoleFamilyType_altova_ID,
	_altova_mi_altova_RoleFamilyType_altova_Name,
	_altova_mi_altova_RoleFamilyType_altova_RefBaseClassPath,
	_altova_mi_altova_RoleFamilyType_altova_Description,
	_altova_mi_altova_RoleFamilyType_altova_Version,
	_altova_mi_altova_RoleFamilyType_altova_Revision,
	_altova_mi_altova_RoleFamilyType_altova_Copyright,
	_altova_mi_altova_RoleFamilyType_altova_AdditionalInformation,
	_altova_mi_altova_RoleFamilyType_altova_Attribute,
	_altova_mi_altova_RoleFamilyType_altova_ExternalInterface,
	_altova_mi_altova_RoleFamilyType_altova_RoleClass,
	_altova_mil_altova_RoleFamilyType
};
enum
{
	_altova_mif_altova_SystemUnitClassType = _altova_mil_altova_RoleFamilyType,
	_altova_mi_altova_SystemUnitClassType_altova_ChangeMode = _altova_mif_altova_SystemUnitClassType,
	_altova_mi_altova_SystemUnitClassType_altova_ID,
	_altova_mi_altova_SystemUnitClassType_altova_Name,
	_altova_mi_altova_SystemUnitClassType_altova_Description,
	_altova_mi_altova_SystemUnitClassType_altova_Version,
	_altova_mi_altova_SystemUnitClassType_altova_Revision,
	_altova_mi_altova_SystemUnitClassType_altova_Copyright,
	_altova_mi_altova_SystemUnitClassType_altova_AdditionalInformation,
	_altova_mi_altova_SystemUnitClassType_altova_Attribute,
	_altova_mi_altova_SystemUnitClassType_altova_ExternalInterface,
	_altova_mi_altova_SystemUnitClassType_altova_InternalElement,
	_altova_mi_altova_SystemUnitClassType_altova_SupportedRoleClass,
	_altova_mi_altova_SystemUnitClassType_altova_InternalLink,
	_altova_mil_altova_SystemUnitClassType
};
enum
{
	_altova_mif_altova_SystemUnitFamilyType = _altova_mil_altova_SystemUnitClassType,
	_altova_mi_altova_SystemUnitFamilyType_altova_ChangeMode = _altova_mif_altova_SystemUnitFamilyType,
	_altova_mi_altova_SystemUnitFamilyType_altova_ID,
	_altova_mi_altova_SystemUnitFamilyType_altova_Name,
	_altova_mi_altova_SystemUnitFamilyType_altova_RefBaseClassPath,
	_altova_mi_altova_SystemUnitFamilyType_altova_Description,
	_altova_mi_altova_SystemUnitFamilyType_altova_Version,
	_altova_mi_altova_SystemUnitFamilyType_altova_Revision,
	_altova_mi_altova_SystemUnitFamilyType_altova_Copyright,
	_altova_mi_altova_SystemUnitFamilyType_altova_AdditionalInformation,
	_altova_mi_altova_SystemUnitFamilyType_altova_Attribute,
	_altova_mi_altova_SystemUnitFamilyType_altova_ExternalInterface,
	_altova_mi_altova_SystemUnitFamilyType_altova_InternalElement,
	_altova_mi_altova_SystemUnitFamilyType_altova_SupportedRoleClass,
	_altova_mi_altova_SystemUnitFamilyType_altova_InternalLink,
	_altova_mi_altova_SystemUnitFamilyType_altova_SystemUnitClass,
	_altova_mil_altova_SystemUnitFamilyType
};
enum
{
	_altova_mif_altova_CAEX_ClassModel = _altova_mil_altova_SystemUnitFamilyType,
	_altova_mi_altova_CAEX_ClassModel_altova_CAEXFile = _altova_mif_altova_CAEX_ClassModel,
	_altova_mil_altova_CAEX_ClassModel
};
enum
{
	_altova_mif_altova_CAEXFileType = _altova_mil_altova_CAEX_ClassModel,
	_altova_mi_altova_CAEXFileType_altova_ChangeMode = _altova_mif_altova_CAEXFileType,
	_altova_mi_altova_CAEXFileType_altova_FileName,
	_altova_mi_altova_CAEXFileType_altova_SchemaVersion,
	_altova_mi_altova_CAEXFileType_altova_Description,
	_altova_mi_altova_CAEXFileType_altova_Version,
	_altova_mi_altova_CAEXFileType_altova_Revision,
	_altova_mi_altova_CAEXFileType_altova_Copyright,
	_altova_mi_altova_CAEXFileType_altova_AdditionalInformation,
	_altova_mi_altova_CAEXFileType_altova_ExternalReference,
	_altova_mi_altova_CAEXFileType_altova_InstanceHierarchy,
	_altova_mi_altova_CAEXFileType_altova_InterfaceClassLib,
	_altova_mi_altova_CAEXFileType_altova_RoleClassLib,
	_altova_mi_altova_CAEXFileType_altova_SystemUnitClassLib,
	_altova_mil_altova_CAEXFileType
};
enum
{
	_altova_mif_altova_DescriptionType = _altova_mil_altova_CAEXFileType,
	_altova_mi_altova_DescriptionType_altova_unnamed = _altova_mif_altova_DescriptionType,
	_altova_mi_altova_DescriptionType_altova_ChangeMode,
	_altova_mil_altova_DescriptionType
};
enum
{
	_altova_mif_altova_VersionType = _altova_mil_altova_DescriptionType,
	_altova_mi_altova_VersionType_altova_unnamed = _altova_mif_altova_VersionType,
	_altova_mi_altova_VersionType_altova_ChangeMode,
	_altova_mil_altova_VersionType
};
enum
{
	_altova_mif_altova_RevisionType = _altova_mil_altova_VersionType,
	_altova_mi_altova_RevisionType_altova_ChangeMode = _altova_mif_altova_RevisionType,
	_altova_mi_altova_RevisionType_altova_Description,
	_altova_mi_altova_RevisionType_altova_Version,
	_altova_mi_altova_RevisionType_altova_Revision,
	_altova_mi_altova_RevisionType_altova_Copyright,
	_altova_mi_altova_RevisionType_altova_AdditionalInformation,
	_altova_mi_altova_RevisionType_altova_RevisionDate,
	_altova_mi_altova_RevisionType_altova_OldVersion,
	_altova_mi_altova_RevisionType_altova_NewVersion,
	_altova_mi_altova_RevisionType_altova_AuthorName,
	_altova_mi_altova_RevisionType_altova_Comment,
	_altova_mil_altova_RevisionType
};
enum
{
	_altova_mif_altova_CopyrightType = _altova_mil_altova_RevisionType,
	_altova_mi_altova_CopyrightType_altova_unnamed = _altova_mif_altova_CopyrightType,
	_altova_mi_altova_CopyrightType_altova_ChangeMode,
	_altova_mil_altova_CopyrightType
};
enum
{
	_altova_mif_altova_ExternalReferenceType = _altova_mil_altova_CopyrightType,
	_altova_mi_altova_ExternalReferenceType_altova_ChangeMode = _altova_mif_altova_ExternalReferenceType,
	_altova_mi_altova_ExternalReferenceType_altova_Path,
	_altova_mi_altova_ExternalReferenceType_altova_Alias,
	_altova_mi_altova_ExternalReferenceType_altova_Description,
	_altova_mi_altova_ExternalReferenceType_altova_Version,
	_altova_mi_altova_ExternalReferenceType_altova_Revision,
	_altova_mi_altova_ExternalReferenceType_altova_Copyright,
	_altova_mi_altova_ExternalReferenceType_altova_AdditionalInformation,
	_altova_mil_altova_ExternalReferenceType
};
enum
{
	_altova_mif_altova_InstanceHierarchyType = _altova_mil_altova_ExternalReferenceType,
	_altova_mi_altova_InstanceHierarchyType_altova_ChangeMode = _altova_mif_altova_InstanceHierarchyType,
	_altova_mi_altova_InstanceHierarchyType_altova_ID,
	_altova_mi_altova_InstanceHierarchyType_altova_Name,
	_altova_mi_altova_InstanceHierarchyType_altova_Description,
	_altova_mi_altova_InstanceHierarchyType_altova_Version,
	_altova_mi_altova_InstanceHierarchyType_altova_Revision,
	_altova_mi_altova_InstanceHierarchyType_altova_Copyright,
	_altova_mi_altova_InstanceHierarchyType_altova_AdditionalInformation,
	_altova_mi_altova_InstanceHierarchyType_altova_InternalElement,
	_altova_mil_altova_InstanceHierarchyType
};
enum
{
	_altova_mif_altova_InterfaceClassLibType = _altova_mil_altova_InstanceHierarchyType,
	_altova_mi_altova_InterfaceClassLibType_altova_ChangeMode = _altova_mif_altova_InterfaceClassLibType,
	_altova_mi_altova_InterfaceClassLibType_altova_ID,
	_altova_mi_altova_InterfaceClassLibType_altova_Name,
	_altova_mi_altova_InterfaceClassLibType_altova_Description,
	_altova_mi_altova_InterfaceClassLibType_altova_Version,
	_altova_mi_altova_InterfaceClassLibType_altova_Revision,
	_altova_mi_altova_InterfaceClassLibType_altova_Copyright,
	_altova_mi_altova_InterfaceClassLibType_altova_AdditionalInformation,
	_altova_mi_altova_InterfaceClassLibType_altova_InterfaceClass,
	_altova_mil_altova_InterfaceClassLibType
};
enum
{
	_altova_mif_altova_RoleClassLibType = _altova_mil_altova_InterfaceClassLibType,
	_altova_mi_altova_RoleClassLibType_altova_ChangeMode = _altova_mif_altova_RoleClassLibType,
	_altova_mi_altova_RoleClassLibType_altova_ID,
	_altova_mi_altova_RoleClassLibType_altova_Name,
	_altova_mi_altova_RoleClassLibType_altova_Description,
	_altova_mi_altova_RoleClassLibType_altova_Version,
	_altova_mi_altova_RoleClassLibType_altova_Revision,
	_altova_mi_altova_RoleClassLibType_altova_Copyright,
	_altova_mi_altova_RoleClassLibType_altova_AdditionalInformation,
	_altova_mi_altova_RoleClassLibType_altova_RoleClass,
	_altova_mil_altova_RoleClassLibType
};
enum
{
	_altova_mif_altova_SystemUnitClassLibType = _altova_mil_altova_RoleClassLibType,
	_altova_mi_altova_SystemUnitClassLibType_altova_ChangeMode = _altova_mif_altova_SystemUnitClassLibType,
	_altova_mi_altova_SystemUnitClassLibType_altova_ID,
	_altova_mi_altova_SystemUnitClassLibType_altova_Name,
	_altova_mi_altova_SystemUnitClassLibType_altova_Description,
	_altova_mi_altova_SystemUnitClassLibType_altova_Version,
	_altova_mi_altova_SystemUnitClassLibType_altova_Revision,
	_altova_mi_altova_SystemUnitClassLibType_altova_Copyright,
	_altova_mi_altova_SystemUnitClassLibType_altova_AdditionalInformation,
	_altova_mi_altova_SystemUnitClassLibType_altova_SystemUnitClass,
	_altova_mil_altova_SystemUnitClassLibType
};
enum
{
	_altova_mif_altova_AttributeDataTypeType = _altova_mil_altova_SystemUnitClassLibType,
	_altova_mil_altova_AttributeDataTypeType = _altova_mif_altova_AttributeDataTypeType
};
enum
{
	_altova_mif_altova_RefSemanticType = _altova_mil_altova_AttributeDataTypeType,
	_altova_mi_altova_RefSemanticType_altova_ChangeMode = _altova_mif_altova_RefSemanticType,
	_altova_mi_altova_RefSemanticType_altova_CorrespondingAttributePath,
	_altova_mi_altova_RefSemanticType_altova_Description,
	_altova_mi_altova_RefSemanticType_altova_Version,
	_altova_mi_altova_RefSemanticType_altova_Revision,
	_altova_mi_altova_RefSemanticType_altova_Copyright,
	_altova_mi_altova_RefSemanticType_altova_AdditionalInformation,
	_altova_mil_altova_RefSemanticType
};
enum
{
	_altova_mif_altova_OrdinalScaledTypeType = _altova_mil_altova_RefSemanticType,
	_altova_mi_altova_OrdinalScaledTypeType_altova_RequiredMaxValue = _altova_mif_altova_OrdinalScaledTypeType,
	_altova_mi_altova_OrdinalScaledTypeType_altova_RequiredValue,
	_altova_mi_altova_OrdinalScaledTypeType_altova_RequiredMinValue,
	_altova_mil_altova_OrdinalScaledTypeType
};
enum
{
	_altova_mif_altova_NominalScaledTypeType = _altova_mil_altova_OrdinalScaledTypeType,
	_altova_mi_altova_NominalScaledTypeType_altova_RequiredValue = _altova_mif_altova_NominalScaledTypeType,
	_altova_mil_altova_NominalScaledTypeType
};
enum
{
	_altova_mif_altova_UnknownTypeType = _altova_mil_altova_NominalScaledTypeType,
	_altova_mi_altova_UnknownTypeType_altova_Requirements = _altova_mif_altova_UnknownTypeType,
	_altova_mil_altova_UnknownTypeType
};
enum
{
	_altova_mif_altova_SupportedRoleClassType = _altova_mil_altova_UnknownTypeType,
	_altova_mi_altova_SupportedRoleClassType_altova_ChangeMode = _altova_mif_altova_SupportedRoleClassType,
	_altova_mi_altova_SupportedRoleClassType_altova_RefRoleClassPath,
	_altova_mi_altova_SupportedRoleClassType_altova_Description,
	_altova_mi_altova_SupportedRoleClassType_altova_Version,
	_altova_mi_altova_SupportedRoleClassType_altova_Revision,
	_altova_mi_altova_SupportedRoleClassType_altova_Copyright,
	_altova_mi_altova_SupportedRoleClassType_altova_AdditionalInformation,
	_altova_mi_altova_SupportedRoleClassType_altova_MappingObject,
	_altova_mil_altova_SupportedRoleClassType
};
enum
{
	_altova_mif_altova_InternalLinkType = _altova_mil_altova_SupportedRoleClassType,
	_altova_mi_altova_InternalLinkType_altova_ChangeMode = _altova_mif_altova_InternalLinkType,
	_altova_mi_altova_InternalLinkType_altova_ID,
	_altova_mi_altova_InternalLinkType_altova_Name,
	_altova_mi_altova_InternalLinkType_altova_RefPartnerSideA,
	_altova_mi_altova_InternalLinkType_altova_RefPartnerSideB,
	_altova_mi_altova_InternalLinkType_altova_Description,
	_altova_mi_altova_InternalLinkType_altova_Version,
	_altova_mi_altova_InternalLinkType_altova_Revision,
	_altova_mi_altova_InternalLinkType_altova_Copyright,
	_altova_mi_altova_InternalLinkType_altova_AdditionalInformation,
	_altova_mil_altova_InternalLinkType
};
enum
{
	_altova_mif_altova_RoleRequirementsType = _altova_mil_altova_InternalLinkType,
	_altova_mi_altova_RoleRequirementsType_altova_ChangeMode = _altova_mif_altova_RoleRequirementsType,
	_altova_mi_altova_RoleRequirementsType_altova_RefBaseRoleClassPath,
	_altova_mi_altova_RoleRequirementsType_altova_Description,
	_altova_mi_altova_RoleRequirementsType_altova_Version,
	_altova_mi_altova_RoleRequirementsType_altova_Revision,
	_altova_mi_altova_RoleRequirementsType_altova_Copyright,
	_altova_mi_altova_RoleRequirementsType_altova_AdditionalInformation,
	_altova_mi_altova_RoleRequirementsType_altova_Attribute,
	_altova_mi_altova_RoleRequirementsType_altova_ExternalInterface,
	_altova_mil_altova_RoleRequirementsType
};
enum
{
	_altova_mif_altova_AttributeNameMappingType = _altova_mil_altova_RoleRequirementsType,
	_altova_mi_altova_AttributeNameMappingType_altova_ChangeMode = _altova_mif_altova_AttributeNameMappingType,
	_altova_mi_altova_AttributeNameMappingType_altova_SystemUnitAttributeName,
	_altova_mi_altova_AttributeNameMappingType_altova_RoleAttributeName,
	_altova_mi_altova_AttributeNameMappingType_altova_Description,
	_altova_mi_altova_AttributeNameMappingType_altova_Version,
	_altova_mi_altova_AttributeNameMappingType_altova_Revision,
	_altova_mi_altova_AttributeNameMappingType_altova_Copyright,
	_altova_mi_altova_AttributeNameMappingType_altova_AdditionalInformation,
	_altova_mil_altova_AttributeNameMappingType
};
enum
{
	_altova_mif_altova_InterfaceNameMappingType = _altova_mil_altova_AttributeNameMappingType,
	_altova_mi_altova_InterfaceNameMappingType_altova_ChangeMode = _altova_mif_altova_InterfaceNameMappingType,
	_altova_mi_altova_InterfaceNameMappingType_altova_SystemUnitInterfaceName,
	_altova_mi_altova_InterfaceNameMappingType_altova_RoleInterfaceName,
	_altova_mi_altova_InterfaceNameMappingType_altova_Description,
	_altova_mi_altova_InterfaceNameMappingType_altova_Version,
	_altova_mi_altova_InterfaceNameMappingType_altova_Revision,
	_altova_mi_altova_InterfaceNameMappingType_altova_Copyright,
	_altova_mi_altova_InterfaceNameMappingType_altova_AdditionalInformation,
	_altova_mil_altova_InterfaceNameMappingType
};
enum
{
	_altova_mif_altova_ExternalInterfaceType = _altova_mil_altova_InterfaceNameMappingType,
	_altova_mi_altova_ExternalInterfaceType_altova_ChangeMode = _altova_mif_altova_ExternalInterfaceType,
	_altova_mi_altova_ExternalInterfaceType_altova_ID,
	_altova_mi_altova_ExternalInterfaceType_altova_Name,
	_altova_mi_altova_ExternalInterfaceType_altova_RefBaseClassPath,
	_altova_mi_altova_ExternalInterfaceType_altova_Description,
	_altova_mi_altova_ExternalInterfaceType_altova_Version,
	_altova_mi_altova_ExternalInterfaceType_altova_Revision,
	_altova_mi_altova_ExternalInterfaceType_altova_Copyright,
	_altova_mi_altova_ExternalInterfaceType_altova_AdditionalInformation,
	_altova_mi_altova_ExternalInterfaceType_altova_Attribute,
	_altova_mil_altova_ExternalInterfaceType
};
enum
{
	_altova_mif_xs_altova_CENTITIES = _altova_mil_altova_ExternalInterfaceType,
	_altova_mil_xs_altova_CENTITIES = _altova_mif_xs_altova_CENTITIES
};
enum
{
	_altova_mif_xs_altova_CENTITY = _altova_mil_xs_altova_CENTITIES,
	_altova_mil_xs_altova_CENTITY = _altova_mif_xs_altova_CENTITY
};
enum
{
	_altova_mif_xs_altova_CID = _altova_mil_xs_altova_CENTITY,
	_altova_mil_xs_altova_CID = _altova_mif_xs_altova_CID
};
enum
{
	_altova_mif_xs_altova_CIDREF = _altova_mil_xs_altova_CID,
	_altova_mil_xs_altova_CIDREF = _altova_mif_xs_altova_CIDREF
};
enum
{
	_altova_mif_xs_altova_CIDREFS = _altova_mil_xs_altova_CIDREF,
	_altova_mil_xs_altova_CIDREFS = _altova_mif_xs_altova_CIDREFS
};
enum
{
	_altova_mif_xs_altova_CNCName = _altova_mil_xs_altova_CIDREFS,
	_altova_mil_xs_altova_CNCName = _altova_mif_xs_altova_CNCName
};
enum
{
	_altova_mif_xs_altova_CNMTOKEN = _altova_mil_xs_altova_CNCName,
	_altova_mil_xs_altova_CNMTOKEN = _altova_mif_xs_altova_CNMTOKEN
};
enum
{
	_altova_mif_xs_altova_CNMTOKENS = _altova_mil_xs_altova_CNMTOKEN,
	_altova_mil_xs_altova_CNMTOKENS = _altova_mif_xs_altova_CNMTOKENS
};
enum
{
	_altova_mif_xs_altova_CNOTATION = _altova_mil_xs_altova_CNMTOKENS,
	_altova_mil_xs_altova_CNOTATION = _altova_mif_xs_altova_CNOTATION
};
enum
{
	_altova_mif_xs_altova_CName = _altova_mil_xs_altova_CNOTATION,
	_altova_mil_xs_altova_CName = _altova_mif_xs_altova_CName
};
enum
{
	_altova_mif_xs_altova_CQName = _altova_mil_xs_altova_CName,
	_altova_mil_xs_altova_CQName = _altova_mif_xs_altova_CQName
};
enum
{
	_altova_mif_xs_altova_CanySimpleType = _altova_mil_xs_altova_CQName,
	_altova_mil_xs_altova_CanySimpleType = _altova_mif_xs_altova_CanySimpleType
};
enum
{
	_altova_mif_xs_altova_CanyType = _altova_mil_xs_altova_CanySimpleType,
	_altova_mi_xs_altova_CanyType_altova_unnamed = _altova_mif_xs_altova_CanyType,
	_altova_mil_xs_altova_CanyType
};
enum
{
	_altova_mif_xs_altova_CanyURI = _altova_mil_xs_altova_CanyType,
	_altova_mil_xs_altova_CanyURI = _altova_mif_xs_altova_CanyURI
};
enum
{
	_altova_mif_xs_altova_Cbase64Binary = _altova_mil_xs_altova_CanyURI,
	_altova_mil_xs_altova_Cbase64Binary = _altova_mif_xs_altova_Cbase64Binary
};
enum
{
	_altova_mif_xs_altova_Cboolean = _altova_mil_xs_altova_Cbase64Binary,
	_altova_mil_xs_altova_Cboolean = _altova_mif_xs_altova_Cboolean
};
enum
{
	_altova_mif_xs_altova_Cbyte = _altova_mil_xs_altova_Cboolean,
	_altova_mil_xs_altova_Cbyte = _altova_mif_xs_altova_Cbyte
};
enum
{
	_altova_mif_xs_altova_Cdate = _altova_mil_xs_altova_Cbyte,
	_altova_mil_xs_altova_Cdate = _altova_mif_xs_altova_Cdate
};
enum
{
	_altova_mif_xs_altova_CdateTime = _altova_mil_xs_altova_Cdate,
	_altova_mil_xs_altova_CdateTime = _altova_mif_xs_altova_CdateTime
};
enum
{
	_altova_mif_xs_altova_Cdecimal = _altova_mil_xs_altova_CdateTime,
	_altova_mil_xs_altova_Cdecimal = _altova_mif_xs_altova_Cdecimal
};
enum
{
	_altova_mif_xs_altova_Cdouble = _altova_mil_xs_altova_Cdecimal,
	_altova_mil_xs_altova_Cdouble = _altova_mif_xs_altova_Cdouble
};
enum
{
	_altova_mif_xs_altova_Cduration = _altova_mil_xs_altova_Cdouble,
	_altova_mil_xs_altova_Cduration = _altova_mif_xs_altova_Cduration
};
enum
{
	_altova_mif_xs_altova_Cfloat = _altova_mil_xs_altova_Cduration,
	_altova_mil_xs_altova_Cfloat = _altova_mif_xs_altova_Cfloat
};
enum
{
	_altova_mif_xs_altova_CgDay = _altova_mil_xs_altova_Cfloat,
	_altova_mil_xs_altova_CgDay = _altova_mif_xs_altova_CgDay
};
enum
{
	_altova_mif_xs_altova_CgMonth = _altova_mil_xs_altova_CgDay,
	_altova_mil_xs_altova_CgMonth = _altova_mif_xs_altova_CgMonth
};
enum
{
	_altova_mif_xs_altova_CgMonthDay = _altova_mil_xs_altova_CgMonth,
	_altova_mil_xs_altova_CgMonthDay = _altova_mif_xs_altova_CgMonthDay
};
enum
{
	_altova_mif_xs_altova_CgYear = _altova_mil_xs_altova_CgMonthDay,
	_altova_mil_xs_altova_CgYear = _altova_mif_xs_altova_CgYear
};
enum
{
	_altova_mif_xs_altova_CgYearMonth = _altova_mil_xs_altova_CgYear,
	_altova_mil_xs_altova_CgYearMonth = _altova_mif_xs_altova_CgYearMonth
};
enum
{
	_altova_mif_xs_altova_ChexBinary = _altova_mil_xs_altova_CgYearMonth,
	_altova_mil_xs_altova_ChexBinary = _altova_mif_xs_altova_ChexBinary
};
enum
{
	_altova_mif_xs_altova_Cint = _altova_mil_xs_altova_ChexBinary,
	_altova_mil_xs_altova_Cint = _altova_mif_xs_altova_Cint
};
enum
{
	_altova_mif_xs_altova_Cinteger = _altova_mil_xs_altova_Cint,
	_altova_mil_xs_altova_Cinteger = _altova_mif_xs_altova_Cinteger
};
enum
{
	_altova_mif_xs_altova_Clanguage = _altova_mil_xs_altova_Cinteger,
	_altova_mil_xs_altova_Clanguage = _altova_mif_xs_altova_Clanguage
};
enum
{
	_altova_mif_xs_altova_Clong = _altova_mil_xs_altova_Clanguage,
	_altova_mil_xs_altova_Clong = _altova_mif_xs_altova_Clong
};
enum
{
	_altova_mif_xs_altova_CnegativeInteger = _altova_mil_xs_altova_Clong,
	_altova_mil_xs_altova_CnegativeInteger = _altova_mif_xs_altova_CnegativeInteger
};
enum
{
	_altova_mif_xs_altova_CnonNegativeInteger = _altova_mil_xs_altova_CnegativeInteger,
	_altova_mil_xs_altova_CnonNegativeInteger = _altova_mif_xs_altova_CnonNegativeInteger
};
enum
{
	_altova_mif_xs_altova_CnonPositiveInteger = _altova_mil_xs_altova_CnonNegativeInteger,
	_altova_mil_xs_altova_CnonPositiveInteger = _altova_mif_xs_altova_CnonPositiveInteger
};
enum
{
	_altova_mif_xs_altova_CnormalizedString = _altova_mil_xs_altova_CnonPositiveInteger,
	_altova_mil_xs_altova_CnormalizedString = _altova_mif_xs_altova_CnormalizedString
};
enum
{
	_altova_mif_xs_altova_CpositiveInteger = _altova_mil_xs_altova_CnormalizedString,
	_altova_mil_xs_altova_CpositiveInteger = _altova_mif_xs_altova_CpositiveInteger
};
enum
{
	_altova_mif_xs_altova_Cshort = _altova_mil_xs_altova_CpositiveInteger,
	_altova_mil_xs_altova_Cshort = _altova_mif_xs_altova_Cshort
};
enum
{
	_altova_mif_xs_altova_Cstring = _altova_mil_xs_altova_Cshort,
	_altova_mil_xs_altova_Cstring = _altova_mif_xs_altova_Cstring
};
enum
{
	_altova_mif_xs_altova_Ctime = _altova_mil_xs_altova_Cstring,
	_altova_mil_xs_altova_Ctime = _altova_mif_xs_altova_Ctime
};
enum
{
	_altova_mif_xs_altova_Ctoken = _altova_mil_xs_altova_Ctime,
	_altova_mil_xs_altova_Ctoken = _altova_mif_xs_altova_Ctoken
};
enum
{
	_altova_mif_xs_altova_CunsignedByte = _altova_mil_xs_altova_Ctoken,
	_altova_mil_xs_altova_CunsignedByte = _altova_mif_xs_altova_CunsignedByte
};
enum
{
	_altova_mif_xs_altova_CunsignedInt = _altova_mil_xs_altova_CunsignedByte,
	_altova_mil_xs_altova_CunsignedInt = _altova_mif_xs_altova_CunsignedInt
};
enum
{
	_altova_mif_xs_altova_CunsignedLong = _altova_mil_xs_altova_CunsignedInt,
	_altova_mil_xs_altova_CunsignedLong = _altova_mif_xs_altova_CunsignedLong
};
enum
{
	_altova_mif_xs_altova_CunsignedShort = _altova_mil_xs_altova_CunsignedLong,
	_altova_mil_xs_altova_CunsignedShort = _altova_mif_xs_altova_CunsignedShort
};
enum
{
	_altova_mif_xs_altova_CstringType = _altova_mil_xs_altova_CunsignedShort,
	_altova_mi_xs_altova_CstringType_altova_unnamed = _altova_mif_xs_altova_CstringType,
	_altova_mil_xs_altova_CstringType
};
enum
{
	_altova_mif_xs_altova_CdateTimeType = _altova_mil_xs_altova_CstringType,
	_altova_mi_xs_altova_CdateTimeType_altova_unnamed = _altova_mif_xs_altova_CdateTimeType,
	_altova_mil_xs_altova_CdateTimeType
};



extern CAEX_ClassModel_DECLSPECIFIER const altova::FacetInfo facets[];
extern CAEX_ClassModel_DECLSPECIFIER const altova::NamespaceInfo namespaces[];
extern CAEX_ClassModel_DECLSPECIFIER const altova::MemberInfo members[];
extern CAEX_ClassModel_DECLSPECIFIER const altova::TypeInfo types[];

}  // namespace CAEX_ClassModel

#endif // _INCLUDED_CAEX_ClassModel_typeinfo_H_
