////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef CAEX_ClassModel_STDAFX_H_INCLUDED
#define CAEX_ClassModel_STDAFX_H_INCLUDED


#ifdef _WIN32 // defined on windows platforms

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#include <windows.h>
#include <tchar.h>

#else // not _WIN32

#include "../Altova/t_defines.h"

#endif  // _WIN32


#include <xercesc/dom/DOM.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>


#ifdef _WIN32 // defined on windows platforms

#ifdef _DEBUG
	#pragma comment(lib, "xerces-c_2D")
#else
	#pragma comment(lib, "xerces-c_2")
#endif


#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information

#endif // _WIN32


#include <iostream>
#include <string>


#include <../Altova/Altova.h>
#include <../Altova/SchemaTypes.h>
#include <../Altova/AltovaException.h>
#include <../Altova/SchemaTypeString.h>
#include <../Altova/SchemaTypeNumber.h>
#include <../Altova/SchemaTypeCalendar.h>
#include <../Altova/SchemaTypeBinary.h>
#include <../AltovaXML/XmlException.h>
#include <../AltovaXML/Doc.h>
#include <../AltovaXML/Node.h>
using namespace altova;


//{{AFX_INSERT_LOCATION}}

#endif // CAEX_ClassModel_STDAFX_H_INCLUDED
