////////////////////////////////////////////////////////////////////////
//
// AltovaXMLAPI.h
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#ifndef ALTOVA_XML_API_H_INCLUDED
#define ALTOVA_XML_API_H_INCLUDED

#ifdef _WIN32

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000


#ifdef ALTOVAXML_EXPORTS
	#define ALTOVAXML_DECLSPECIFIER __declspec(dllexport)
	#define ALTOVAXML_EXPIMP_TEMPLATE
#else
	#define ALTOVAXML_DECLSPECIFIER __declspec(dllimport)
	#define ALTOVAXML_EXPIMP_TEMPLATE extern
#endif

#ifndef _MFC_VER
	#pragma warning(disable: 4660)
	#pragma warning(disable: 4231)
	#pragma warning(disable: 4251)
#endif

#else // not _WIN32

#define ALTOVAXML_DECLSPECIFIER
#define ALTOVAXML_EXPIMP_TEMPLATE

#endif // _WIN32

#endif // ALTOVA_XML_API_H_INCLUDED
