////////////////////////////////////////////////////////////////////////
//
// Altova.h
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef ALTOVADEFS_H_INCLUDED
#define ALTOVADEFS_H_INCLUDED

#ifdef _WIN32

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000


#ifdef ALTOVA_EXPORTS
#define ALTOVA_DECLSPECIFIER __declspec(dllexport)
#else   // not ALTOVA_EXPORTS
#define ALTOVA_DECLSPECIFIER __declspec(dllimport)
#endif  // ALTOVA_EXPORTS

#else  // not _WIN32

#define ALTOVA_DECLSPECIFIER  

#endif // _WIN32

#include "common_typedefs.h"
//#include "AltovaException.h"

#endif // ALTOVADEFS_H_INCLUDED
