////////////////////////////////////////////////////////////////////////
//
// CAEX_ClassModelTest.h
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef CAEX_ClassModelTest_H_INCLUDED
#define CAEX_ClassModelTest_H_INCLUDED

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#include "Resource.h"


#endif // CAEX_ClassModelTest_H_INCLUDED
