////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef CAEX_ClassModelTest_STDAFX_H_INCLUDED
#define CAEX_ClassModelTest_STDAFX_H_INCLUDED

#ifdef _WIN32

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#include <windows.h>
#include <tchar.h>

#else // not _WIN32

#include "t_defines.h"

#endif // _WIN32


#include <xercesc/dom/DOM.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>

#ifdef _DEBUG
	#pragma comment(lib, "xerces-c_2D")
#else
	#pragma comment(lib, "xerces-c_2")
#endif

#include <iostream>
#include <string>


#include <Altova.h>
#include <SchemaTypes.h>
#include <AltovaException.h>
#include <SchemaTypeString.h>
#include <SchemaTypeNumber.h>
#include <SchemaTypeCalendar.h>
#include <SchemaTypeBinary.h>
#include <XmlException.h>
#include <Doc.h>
#include <Node.h>
using namespace altova;


//{{AFX_INSERT_LOCATION}}

#endif // CAEX_ClassModelTest_STDAFX_H_INCLUDED
