////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2008 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef ALTOVA_STDAFX_H_INCLUDED
#define ALTOVA_STDAFX_H_INCLUDED


#ifdef _WIN32 // defined on windows platforms

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#include <windows.h>
#include <tchar.h>

#else // not _WIN32

#include "t_defines.h"

#endif // _WIN32


#include <xercesc/dom/DOM.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>


#ifdef _WIN32 // defined on windows platforms

#ifdef _DEBUG
	#pragma comment(lib, "xerces-c_2D")
#else
	#pragma comment(lib, "xerces-c_2")
#endif // _DEBUG

#endif // _WIN32


#include <iostream>
#include <string>


//{{AFX_INSERT_LOCATION}}

#endif // ALTOVA_STDAFX_H_INCLUDED
